app = "cairo-transport"
primary_region = "iad"

[env]
PYTHONUNBUFFERABLE = "true"
FLASK_ENV = "production"
PORT = "8080"

[http_service]
internal_port = 8080
force_https = true

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512
